### PR TITLE
Changes for adapted player model

### PR DESCRIPTION
**Pull request by Rogier-5**
Fixes issue #9

The new player model is used in minetest_game since 25 nov 2016,
and 3d_armor since 27 nov 2016

Dependency on 3d_armor was removed, as it is no longer needed

### CODE REVIEW

**Comment by Rui-Minetest** [comment]
After PR is merged, I'll split it and create a branch which for support older one.
I think the best way is making the user can decide which one to choice on download link.

**Comment by Rogier-5** [comment]
@Rui-Minetest I think that would be confusing, as there would be two different mods with the same name. A player using both older and newer player models for different worlds could find it difficult to get each world use the right version.

Thinking of that: I'll have another look at the PR: the choice of model should be configured differently. E.g. a setting in minetest.conf, or maybe even somewhere else altogether. Maybe even a change to minetest_game (and 3d_armor) as well, so that the selected version of the model is configured at the point where the model is configured as well.

**Comment by Rui-Minetest** [comment]
We can use `settingtypes.txt`.

**Comment by Rogier-5** [comment]
Pushed a new version. It now uses a setting that can be configured per world.

**Comment by Rui-Minetest** [comment]
> It now uses a setting that can be configured per world.

Was world-specific setting implemented?

**Comment by Rogier-5** [comment]
I have used the `settingtypes.txt` infrastructure. That means that the configuration is in `minetest.conf`. That is what is usually desired, as different worlds that use the same `minetest.conf` also use the same subgames and same mods. So they'll usually have the same player model.

**Comment by Rui-Minetest** [comment]
I see.

Merged: https://github.com/minetest-mods/playeranim/commit/0ca8e5a3aad630657d17ba801eede61cb1ff7065

**Pull request merged**
